name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    permissions:
      contents: write
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # O comando de construção do seu projetosd

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # O nome do branch para onde deseja enviar os ativos
          FOLDER: build # O diretório onde seus ativos são gerados
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # O GitHub adicionará automaticamente - você não precisa se preocupar em obter um token
          MESSAGE: "Build: ({sha}) {msg}" # A mensagem de commitzx
